# Slack API
SLACK_CLIENT_ID = ""
SLACK_CLIENT_SECRET = ""
SLACK_VERIFICATION_TOKEN = ""
SLACK_LEGACY_TOKEN = ""

# SQLAlchemy
SQLALCHEMY_DATABASE_URI = "sqlite:///instance/test_sqlite.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False