# Slack API
SLACK_CLIENT_ID = "TEST_CLIENT_ID"
SLACK_CLIENT_SECRET = "TEST_CLIENT_SECRET"
SLACK_VERIFICATION_TOKEN = "TEST_VERIFICATION_TOKEN"
SLACK_LEGACY_TOKEN = "TEST_LEGACY_TOKEN"

# SQLAlchemy
SQLALCHEMY_DATABASE_URI = "sqlite://"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Flask Config
DEBUG = False